pipeline {
    agent any
    environment {
        rpmJenkinsAuthenticationId = '3af1598d-3a55-402f-b59f-c12a8c34cad3'
        distroSpace = 'distro'
        distroSourceSpace = 'distroSource'
        distroSourceRpmSpace = "${distroSourceSpace}/rpms"
        upgradeDir = "ris-huaweiit-upgrade-133"
        upgradeSrcDir = "${upgradeDir}/packages"
        degradeSrcDir = "${upgradeDir}/old"
    }
    stages {
        stage('prebuild') {
            steps {
                echo 'prebuild rpm'
                script {
                    echo "to reset workspace"
                    resetDistroWorkspace()
                }
            }
        }
        stage('make the upgrade repos up to date') {
            steps {
                echo 'make the upgrade repos up to date TODO'
            }
        }
        stage('use template of upgrade directory in rpm-repos') {
            steps {
                script {
                    def upgradeDirPathInRepos = "../rpm-repos-trigger/distro/upgrade/${upgradeDir}" + ""
                    def permissionTable = [
                            'upgrade'                    : '700',
                            'check_scripts/pre_check.sh' : '755',
                            'check_scripts/pre_backup.sh': '755'
                    ]
                    if (!fileExists(upgradeDirPathInRepos)) {
                        error "con not find the path: ${upgradeDirPathInRepos}"
                    }
                    sh "\\cp -rf ${upgradeDirPathInRepos} ./${distroSpace}/"
                    if (!fileExists("${distroSpace}/${upgradeDir}")) {
                        error "failed to copy upgrade directory: ${upgradeDir} to workspace"
                    }
                    echo "copied template"
                    permissionTable.each { item ->
                        sh "chmod ${item.value} ${distroSpace}/${upgradeDir}/${item.key}"
                    }
                }
            }
        }
        stage('build and get official rpm') {
            environment {
                jenkinsHost = "repos.shterm.com/jenkins"
                rpmDeployHost = "10.10.0.12"
                rpmDeployPath = "yum/shterm/x86_64/Packages"
                rpmDeployFullPath = "${rpmDeployHost}/${rpmDeployPath}"
                build3Proxy = 'false'
                buildFileClient = 'true'
            }
            failFast true
            parallel {
                stage('shterm2-fileclient') {
                    when {
                        environment name: 'buildFileClient', value: 'true'
                    }
                    environment {
                        buildProject = 'shterm2-fileclient'
                        version = "3.3.8"
                        release = "133.aca"
                        buildArch = "noarch"
                        jobName = "shterm2-fileclient-3.3.8-c-huaweiit"
                        rpmFilename = "${buildProject}-${version}-${release}.${buildArch}.rpm"
                        downloadUrl = "http://${rpmDeployFullPath}/${rpmFilename}"
                        srcRpmPath = "${distroSourceRpmSpace}/${rpmFilename}"
                        distRpmDir = "${distroSpace}/${upgradeSrcDir}/common"
                        distRpmPath = "${distRpmDir}/${rpmFilename}"
                    }
                    steps {
                        echo 'build shterm2-fileclient rpm'
                        script {
                            int timeToPolling = 10
                            def jobUrl = "http://${jenkinsHost}/view/HUAWEI/job/3.3.8-c-huaweiit/job/${jobName}" + ""
                            int nextBuildNumber = getNextBuilderNumber(buildProject, rpmJenkinsAuthenticationId, jobUrl)
                            echo("the nextBuildNumber of ${buildProject} : ${nextBuildNumber}")

                            createBuild(buildProject, rpmJenkinsAuthenticationId, jobUrl)

                            pollBuildStatus(nextBuildNumber, timeToPolling, buildProject, rpmJenkinsAuthenticationId, jobUrl)

                            echo "downloading ${buildProject} rpm to workspace"
                            sh "curl -s -R ${downloadUrl} -o ${srcRpmPath}"
                            if (fileExists(srcRpmPath)) {
                                echo "succeed to download ${buildProject}"
                            } else {
                                error "failed to download ${buildProject}"
                            }
                            createDirIfNotExist(distRpmDir)
                            sh "cp ${srcRpmPath} ${distRpmPath}"
                        }
                    }
                }
                stage('3proxy') {
                    when {
                        environment name: 'build3Proxy', value: 'true'
                    }
                    environment {
                        buildProject = '3proxy'
                        version = "0.9.3"
                        release = "133.aca"
                        buildArch = "x86_64"
                        jobName = "3proxy-3.3.8-c-huaweiit"
                    }
                    steps {
                        echo 'build 3proxy rpm'

                        script {
                            int timeToPolling = 10
                            def jobUrl = "http://${jenkinsHost}/view/HUAWEI/job/3.3.8-c-huaweiit/job/${jobName}" + ""
                            int nextBuildNumber = getNextBuilderNumber(buildProject, rpmJenkinsAuthenticationId, jobUrl)
                            echo("the nextBuildNumber of ${buildProject} : ${nextBuildNumber}")

                            createBuild(buildProject, rpmJenkinsAuthenticationId, jobUrl)

                            pollBuildStatus(nextBuildNumber, timeToPolling, buildProject, rpmJenkinsAuthenticationId, jobUrl)

                            echo "downloading ${buildProject} rpm to workspace"
                            def rpmFilename = "${buildProject}-${version}-${release}.${buildArch}.rpm" + ""
                            sh "curl -s -R -O http://${rpmDeployHost}/${rpmDeployPath}/${rpmFilename}"
                            if (fileExists(rpmFilename)) {
                                echo "succeed to download ${buildProject}"
                            } else {
                                error "failed to download ${buildProject}"
                            }
                        }
                    }
                }
            }
        }
        stage('get official old rpm') {
            steps {
                echo 'get official old rpm'
            }
        }
        stage('get official new script') {
            steps {
                echo 'get official new script'
            }
        }
        stage('get official old script') {
            steps {
                echo 'get official old script'
            }
        }
        stage('get lib') {
            steps {
                echo 'get lib'
            }
        }
        stage('deploy') {
            steps {
                echo 'deploy'
            }
        }
    }
}

private void resetDistroWorkspace() {
    echo "to delete dir"
    sh "rm -rf ${distroSpace}"
    echo "to create dir"
    sh "mkdir ${distroSpace}"
    echo "to create sdir"
    createDirIfNotExist(distroSourceSpace)
    createDirIfNotExist(distroSourceRpmSpace)
}

private void createDirIfNotExist(dirPath) {
    if (!fileExists(dirPath)) {
        sh "mkdir ${dirPath}"
    }
}

private void pollBuildStatus(int buildNumber, int timeToPolling, buildProject, authentication, jobUrl) {
    while (true) {
        def buildInfoResponse = httpRequest authentication: authentication, validResponseCodes: '200,404',
                url: "${jobUrl}/${buildNumber}/api/json?pretty=true"
        if (buildInfoResponse.status == 404) {
            echo "The created build is not building, wait for building."
            sleep timeToPolling
            continue
        }
        if (buildInfoResponse.status != 200) {
            error("failed to get build information for ${buildProject}")
        }
        def jsonBuildInfoResponse = readJSON text: buildInfoResponse.content
        boolean building = jsonBuildInfoResponse.building
        def result = jsonBuildInfoResponse.result
        if (building) {
            echo "still in building, wait ${timeToPolling} seconds"
        } else {
            if ('SUCCESS' != result) {
                error("failed to build ${buildProject}")
            } else {
                echo "succeed to build ${buildProject}"
                break
            }
        }
        sleep timeToPolling
    }
}

private void createBuild(buildProject, authentication, jobUrl) {
    def newBuildResponse = httpRequest authentication: authentication, url: "${jobUrl}/build", httpMode: 'POST'
    if (newBuildResponse.status != 201) {
        error("failed to create build of ${buildProject}")
    }
    echo "succeed to create build of ${buildProject}"
}

private int getNextBuilderNumber(buildProject, authentication, jobUrl) {
    def response = httpRequest authentication: authentication, url: "${jobUrl}/api/json?pretty=true"
    if (response.status != 200) {
        error("failed to get job information for ${buildProject}")
    }
    echo "succeed to get job information of ${buildProject}"
    def jsonResponse = readJSON text: response.content
    int nextBuildNumber = jsonResponse.nextBuildNumber
    return nextBuildNumber
}