map = ['']

pipeline {
    agent any
    stages {
        stage('prebuild') {
            steps {
                echo 'prebuild rpm'
            }
        }
        stage('build official rpm') {
            failFast: false
            parallel{
                stage('build shterm2-fileclient'){
                    steps{
                        echo 'build shterm2-fileclient rpm'
                    }
                }
                stage('build 3proxy'){
                    steps{
                        echo 'build 3proxy rpm'
                    }
                }
            }
        }
        stage('get official old rpm') {
            steps {
                echo 'get official old rpm'
            }
        }
        stage('get official new script') {
            steps {
                echo 'get official new script'
            }
        }
        stage('get official old script') {
            steps {
                echo 'get official old script'
            }
        }
        stage('get lib') {
            steps {
                echo 'get lib'
            }
        }
        stage('build upgrade package') {
            steps {
                echo 'build upgrade package'
            }
        }
        stage('deploy') {
            steps {
                echo 'deploy'
            }
        }
    }
}